package(default_visibility = ["//visibility:public"])

load("//py:toolchain.bzl", "samer_binary")

samer_binary(
    name = "sameryo",
)

toolchain_type(
    name = "samer_toolchain",
)

toolchain_type(
    name = "samer_bootstrap_toolchain",
)

samer_binary(
    name = "hellothere",
)

toolchain_type(
    name = "samer_standalone_toolchain",
)
